<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [5]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [6]:
import folium
import pandas as pd

In [7]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

In [8]:
from js import fetch
import io
import pandas as pd

URL = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv"

resp = await fetch(URL)
data = await resp.arrayBuffer()
spacex_csv_file = io.BytesIO(data.to_bytes())
spacex_df = pd.read_csv(spacex_csv_file)

print("✅ Data loaded!")
print(f"Shape: {spacex_df.shape}")
spacex_df.head()

✅ Data loaded!
Shape: (56, 13)

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356

In [9]:
## Task 1: Mark all launch sites on a map
import folium

# Get unique launch sites
unique_sites = spacex_df[['Launch Site', 'Lat', 'Long']].drop_duplicates()
print("Unique launch sites:")
print(unique_sites)

# Find center for the map
center_lat = unique_sites['Lat'].mean()
center_lon = unique_sites['Long'].mean()

# Create the map
launch_map = folium.Map(location=[center_lat, center_lon], zoom_start=5)

# Add markers for each launch site
for idx, row in unique_sites.iterrows():
    folium.Marker(
        location=[row['Lat'], row['Long']],
        popup=row['Launch Site'],
        icon=folium.Icon(color='red', icon='rocket')
    ).add_to(launch_map)

# Display the map
launch_map

Unique launch sites:
     Launch Site        Lat        Long
0    CCAFS LC-40  28.562302  -80.577356
26   VAFB SLC-4E  34.632834 -120.610745
36    KSC LC-39A  28.573255  -80.646895
49  CCAFS SLC-40  28.563197  -80.576820

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

Mark the success/failed launches for each site on the map.

In [20]:
# Create a map centered at the average coordinates
center_lat = spacex_df['Lat'].mean()
center_lon = spacex_df['Long'].mean()

launch_map = folium.Map(location=[center_lat, center_lon], zoom_start=5)

# Add markers for EACH launch (not just unique sites)
# Green marker for success (class=1), Red marker for failure (class=0)

for idx, row in spacex_df.iterrows():
    # Choose color based on success/failure
    color = 'green' if row['class'] == 1 else 'red'
    
    folium.Marker(
        location=[row['Lat'], row['Long']],
        popup=f"{row['Launch Site']}<br>Outcome: {row['Landing Outcome']}<br>Success: {row['class']}",
        icon=folium.Icon(color=color, icon='rocket')
    ).add_to(launch_map)

# Display the map
launch_map

In [19]:
# Download and read the `spacex_launch_geo.csv`
from js import fetch
import io
import pandas as pd

URL = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv"

resp = await fetch(URL)
data = await resp.arrayBuffer()
spacex_csv_file = io.BytesIO(data.to_bytes())
spacex_df = pd.read_csv(spacex_csv_file)

print("✅ Data loaded!")
print(f"Shape: {spacex_df.shape}")
spacex_df.head()

✅ Data loaded!
Shape: (56, 13)

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356

Now, you can take a look at what are the coordinates for each site.

In [5]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [21]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [32]:
## Write your answer

import folium

# NASA Johnson Space Center coordinates
nasa_coordinate = [29.559684888503615, -95.0830971930759]

# Create the map (same format as Task 1)
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

# Add circle (same format as Task 1 markers)
circle = folium.Circle(
    nasa_coordinate, 
    radius=1000, 
    color='#d35400', 
    fill=True,
    popup='NASA Johnson Space Center'
).add_to(site_map)

# Add marker (same format as Task 1)
marker = folium.Marker(
    nasa_coordinate,
    popup='NASA Johnson Space Center',
    icon=folium.Icon(color='orange')
).add_to(site_map)

# Display the map (SAME as Task 1)
site_map

In [33]:
import folium

# NASA Johnson Space Center coordinates
nasa_coordinate = [29.559684888503615, -95.0830971930759]

# Create map
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

# Add circle
circle = folium.Circle(
    nasa_coordinate, 
    radius=1000, 
    color='#d35400', 
    fill=True,
    popup='NASA Johnson Space Center'
).add_to(site_map)

# Add marker
marker = folium.Marker(
    nasa_coordinate,
    popup='NASA Johnson Space Center',
    icon=folium.Icon(color='orange')
).add_to(site_map)

# Display
site_map

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [36]:
import folium
from folium.features import DivIcon

# Create a map centered at the average coordinates
center_lat = spacex_df['Lat'].mean()
center_lon = spacex_df['Long'].mean()

site_map = folium.Map(location=[center_lat, center_lon], zoom_start=5)

# Get unique launch sites
unique_sites = spacex_df[['Launch Site', 'Lat', 'Long']].drop_duplicates()

# Add circle and marker for each launch site
for idx, row in unique_sites.iterrows():
    coordinate = [row['Lat'], row['Long']]
    site_name = row['Launch Site']
    
    # Add circle
    folium.Circle(
        coordinate,
        radius=1000,
        color='#000000',
        fill=True,
        popup=site_name
    ).add_to(site_map)
    
    # Add marker with label
    folium.map.Marker(
        coordinate,
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12px; color:#d35400;"><b>{site_name}</b></div>'
        )
    ).add_to(site_map)

# Display the map
site_map

The generated map with marked launch sites should look similar to the following:

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?

Answer: Yes, all launch sites are relatively close to the Equator.

Explanation:

CCAFS LC-40 (Cape Canaveral): ~28.5°N

CCAFS SLC-40 (Cape Canaveral): ~28.5°N

KSC LC-39A (Kennedy Space Center): ~28.5°N

VAFB SLC-4E (Vandenberg): ~34.6°N

Why? Launching closer to the Equator takes advantage of Earth's rotational speed (higher at Equator), giving rockets an extra velocity boost, saving fuel and allowing heavier payloads.


*   Are all launch sites in very close proximity to the coast?

Answer: Yes, all launch sites are located directly on or very near the coast.

Explanation:

Cape Canaveral sites (FL) : Directly on Atlantic Ocean coast

KSC (FL) : Directly on Atlantic Ocean coast

Vandenberg (CA) : Directly on Pacific Ocean coast

Why? Rockets launch over water for safety reasons:

If a rocket fails, debris falls into the ocean, not on populated areas

Allows launches in multiple directions without endangering cities

First stage boosters can land on drone ships in the ocean

Also please try to explain your findings.

In [44]:
# Task 2: Mark the success/failed launches for each site on the map

import folium

# Create a map centered at the average coordinates
center_lat = spacex_df['Lat'].mean()
center_lon = spacex_df['Long'].mean()

launch_map = folium.Map(location=[center_lat, center_lon], zoom_start=5)

# Add markers for EACH launch
# Green marker = Success (class=1)
# Red marker = Failure (class=0)

for idx, row in spacex_df.iterrows():
    # Choose color based on success/failure
    color = 'green' if row['class'] == 1 else 'red'
    
    folium.Marker(
        location=[row['Lat'], row['Long']],
        popup=f"Site: {row['Launch Site']}<br>Outcome: {row['Landing Outcome']}<br>Success: {row['class']}",
        icon=folium.Icon(color=color, icon='rocket')
    ).add_to(launch_map)

# Display the map
launch_map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [40]:
spacex_df.tail(10)

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
46,43,2017-10-11,22:53:00,F9 FT B1031.2,KSC LC-39A,SES-11 / EchoStar 105,5200.00,GTO,SES EchoStar,Success (drone ship),1,28.573255,-80.646895
47,44,2017-10-30,19:34:00,F9 B4 B1042.1,KSC LC-39A,Koreasat 5A,3500.00,GTO,KT Corporation,Success (drone ship),1,28.573255,-80.646895
48,54,2018-05-11,20:14:00,F9 B5 B1046.1,KSC LC-39A,Bangabandhu-1,3600.00,GTO,Thales-Alenia/BTRC,Success (drone ship),1,28.573255,-80.646895
49,45,2017-12-15,15:36:00,F9 FT B1035.2,CCAFS SLC-40,SpaceX CRS-13,2205.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.563197,-80.576820
50,47,2018-01-08,1:00:00,F9 B4 B1043.1,CCAFS SLC-40,Zuma,3696.65,LEO,Northrop Grumman,Success (ground pad),1,28.563197,-80.576820
51,48,2018-01-31,21:25:00,F9 FT B1032.2,CCAFS SLC-40,GovSat-1 / SES-16,4230.00,GTO,SES,Controlled (ocean),0,28.563197,-80.576820
52,50,2018-03-06,5:33:00,F9 B4 B1044,CCAFS SLC-40,Hispasat 30W-6 PODSat,6092.00,GTO,Hispasat NovaWurks,No attempt,0,28.563197,-80.576820
53,52,2018-04-02,20:30:00,F9 B4 B1039.2,CCAFS SLC-40,SpaceX CRS-14,2647.00,LEO (ISS),NASA (CRS),No attempt,0,28.563197,-80.576820
54,53,2018-04-18,22:51:00,F9 B4 B1045.1,CCAFS SLC-40,Transiting Exoplanet Survey Satellite (TESS),362.00,HEO,NASA (LSP),Success (drone ship),1,28.563197,-80.576820
55,56,2018-06-04,4:45:00,F9 B4 B1040.2,CCAFS SLC-40,SES-12,5384.00,GTO,SES,No attempt,0,28.563197,-80.576820

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [46]:
marker_cluster = MarkerCluster()

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

In [49]:

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red

# Create a new column 'marker_color' based on the 'class' value
spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'green' if x == 1 else 'red')

# Verify the new column
print(spacex_df[['class', 'marker_color']].head(10))
# Check the last 10 rows
print(spacex_df[['class', 'marker_color']].tail(10))

   class marker_color
0      0          red
1      0          red
2      0          red
3      0          red
4      0          red
5      0          red
6      0          red
7      0          red
8      0          red
9      0          red
    class marker_color
46      1        green
47      1        green
48      1        green
49      1        green
50      1        green
51      0          red
52      0          red
53      0          red
54      1        green
55      0          red

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [50]:
import folium
from folium.plugins import MarkerCluster

# Create map
center_lat = spacex_df['Lat'].mean()
center_lon = spacex_df['Long'].mean()

site_map = folium.Map(location=[center_lat, center_lon], zoom_start=5)

# Create marker cluster
marker_cluster = MarkerCluster().add_to(site_map)

# Add markers to cluster
for index, record in spacex_df.iterrows():
    folium.Marker(
        location=[record['Lat'], record['Long']],
        popup=f"Site: {record['Launch Site']}<br>Outcome: {record['Landing Outcome']}<br>Success: {record['class']}",
        icon=folium.Icon(color='white', icon_color=record['marker_color'], icon='rocket')
    ).add_to(marker_cluster)

# Display map
site_map

In [ ]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    # marker = folium.Marker(...)
    marker_cluster.add_child(marker)

site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

In [54]:
# TASK 3: Calculate the distances between a launch site to its proximities


from math import sin, cos, sqrt, atan2, radians
import folium
from folium.plugins import MarkerCluster

# Function to calculate distance between two coordinates (in km)
def calculate_distance(lat1, lon1, lat2, lon2):
    # Earth radius in kilometers
    R = 6373.0
    
    # Convert to radians
    lat1_r = radians(lat1)
    lon1_r = radians(lon1)
    lat2_r = radians(lat2)
    lon2_r = radians(lon2)
    
    # Differences
    dlon = lon2_r - lon1_r
    dlat = lat2_r - lat1_r
    
    # Haversine formula
    a = sin(dlat / 2)**2 + cos(lat1_r) * cos(lat2_r) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    
    return R * c

# Get unique launch sites
unique_sites = spacex_df[['Launch Site', 'Lat', 'Long']].drop_duplicates()
print("=" * 60)
print("LAUNCH SITES AND THEIR COORDINATES")
print("=" * 60)
for idx, row in unique_sites.iterrows():
    print(f"{row['Launch Site']}: Lat={row['Lat']:.5f}, Lon={row['Long']:.5f}")

# Calculate distances between launch sites
print("\n" + "=" * 60)
print("DISTANCES BETWEEN LAUNCH SITES")
print("=" * 60)

for i in range(len(unique_sites)):
    for j in range(i+1, len(unique_sites)):
        site1 = unique_sites.iloc[i]
        site2 = unique_sites.iloc[j]
        dist = calculate_distance(site1['Lat'], site1['Long'], site2['Lat'], site2['Long'])
        print(f"{site1['Launch Site']} → {site2['Launch Site']}: {dist:.2f} km")

# Find nearest city/coast for each launch site
print("\n" + "=" * 60)
print("DISTANCE TO NEAREST COASTLINE (APPROXIMATE)")
print("=" * 60)

# Approximate coastline coordinates for Florida and California
coastline_points = {
    'Florida East Coast': [28.5, -80.5],
    'Florida Coast (Canaveral)': [28.5, -80.55],
    'California Coast': [34.6, -120.6]
}

for idx, row in unique_sites.iterrows():
    site_name = row['Launch Site']
    site_lat = row['Lat']
    site_lon = row['Long']
    
    # For Florida sites
    if 'CCAFS' in site_name or 'KSC' in site_name:
        coast_coord = [28.5, -80.55]
        dist = calculate_distance(site_lat, site_lon, coast_coord[0], coast_coord[1])
        print(f"{site_name}: ~{dist:.2f} km from Florida coast")
    
    # For California site
    elif 'VAFB' in site_name:
        coast_coord = [34.6, -120.6]
        dist = calculate_distance(site_lat, site_lon, coast_coord[0], coast_coord[1])
        print(f"{site_name}: ~{dist:.2f} km from California coast")

============================================================
LAUNCH SITES AND THEIR COORDINATES
============================================================
CCAFS LC-40: Lat=28.56230, Lon=-80.57736
VAFB SLC-4E: Lat=34.63283, Lon=-120.61075
KSC LC-39A: Lat=28.57325, Lon=-80.64690
CCAFS SLC-40: Lat=28.56320, Lon=-80.57682

============================================================
DISTANCES BETWEEN LAUNCH SITES
============================================================
CCAFS LC-40 → VAFB SLC-4E: 3827.04 km
CCAFS LC-40 → KSC LC-39A: 6.90 km
CCAFS LC-40 → CCAFS SLC-40: 0.11 km
VAFB SLC-4E → KSC LC-39A: 3820.25 km
VAFB SLC-4E → CCAFS SLC-40: 3827.06 km
KSC LC-39A → CCAFS SLC-40: 6.94 km

============================================================
DISTANCE TO NEAREST COASTLINE (APPROXIMATE)
============================================================
CCAFS LC-40: ~7.43 km from Florida coast
VAFB SLC-4E: ~3.78 km from California coast
KSC LC-39A: ~12.49 km from Florida coast
CCAFS SLC-40: ~7.50 km from Florida coast

In [57]:
## To visualize distances on the map:

import folium

# Get unique launch sites
unique_sites = spacex_df[['Launch Site', 'Lat', 'Long']].drop_duplicates()

# Calculate center
center_lat = unique_sites['Lat'].mean()
center_lon = unique_sites['Long'].mean()

# Create map
site_map = folium.Map(location=[center_lat, center_lon], zoom_start=5)

# Add markers and circles
for idx, row in unique_sites.iterrows():
    coordinate = [row['Lat'], row['Long']]
    site_name = row['Launch Site']
    
    # Marker
    folium.Marker(
        coordinate,
        popup=site_name,
        icon=folium.Icon(color='red', icon='info-sign')
    ).add_to(site_map)
    
    # 100km circle
    folium.Circle(
        coordinate,
        radius=100000,
        color='blue',
        fill=False,
        popup='100km'
    ).add_to(site_map)
    
    # 500km circle
    folium.Circle(
        coordinate,
        radius=500000,
        color='green',
        fill=False,
        popup='500km'
    ).add_to(site_map)

# Display the map (inline)
site_map

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [15]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [17]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [12]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

from math import sin, cos, sqrt, atan2, radians
import folium
from folium.features import DivIcon

# Function to calculate distance
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0
    lat1_r = radians(lat1)
    lon1_r = radians(lon1)
    lat2_r = radians(lat2)
    lon2_r = radians(lon2)
    dlon = lon2_r - lon1_r
    dlat = lat2_r - lat1_r
    a = sin(dlat / 2)**2 + cos(lat1_r) * cos(lat2_r) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c

# Launch site coordinates (CCAFS LC-40)
launch_site_lat = 28.56230
launch_site_lon = -80.57736

# Closest coastline coordinates (from mouse position on map)
coastline_lat = 28.56230
coastline_lon = -80.55000

# Calculate distance
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

print(f"Distance from launch site to coastline: {distance_coastline:.2f} km")

# Create map
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=13)

# Add launch site marker
folium.Marker(
    [launch_site_lat, launch_site_lon],
    popup="Launch Site",
    icon=folium.Icon(color='red', icon='rocket')
).add_to(site_map)

# Add coastline marker with distance
folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html=f'<div style="font-size: 12px; color:#d35400;"><b>{distance_coastline:.2f} km</b></div>'
    )
).add_to(site_map)

# Add line between launch site and coastline
folium.PolyLine(
    [[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]],
    color='blue',
    weight=2
).add_to(site_map)

site_map

Distance from launch site to coastline: 2.67 km

In [13]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 
# for example
# distance_marker = folium.Marker(
#    coordinate,
#    icon=DivIcon(
#        icon_size=(20,20),
#        icon_anchor=(0,0),
#        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
#        )
#    )




from math import sin, cos, sqrt, atan2, radians
import folium
from folium.features import DivIcon

# Function to calculate distance
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0
    lat1_r = radians(lat1)
    lon1_r = radians(lon1)
    lat2_r = radians(lat2)
    lon2_r = radians(lon2)
    dlon = lon2_r - lon1_r
    dlat = lat2_r - lat1_r
    a = sin(dlat / 2)**2 + cos(lat1_r) * cos(lat2_r) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c

# Launch site coordinates (CCAFS LC-40)
launch_site_lat = 28.56230
launch_site_lon = -80.57736

# Closest coastline coordinates (from mouse position on map)
coastline_lat = 28.56230
coastline_lon = -80.55000

# Calculate distance
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

# Create map
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=13)

# Add launch site marker
folium.Marker(
    [launch_site_lat, launch_site_lon],
    popup="Launch Site",
    icon=folium.Icon(color='red', icon='rocket')
).add_to(site_map)

# Create and add marker on coastline point with distance display
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12px; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_coastline),
    )
)
distance_marker.add_to(site_map)

# Add line between launch site and coastline
folium.PolyLine(
    [[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]],
    color='blue',
    weight=2,
    popup=f'Distance: {distance_coastline:.2f} km'
).add_to(site_map)

# Display map
site_map

print(f"✅ Distance from launch site to coastline: {distance_coastline:.2f} km")

✅ Distance from launch site to coastline: 2.67 km

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

Your updated map with distance line should look like the following screenshot:

In [21]:
## Your updated map with distance line should look like the following screenshot:

from math import sin, cos, sqrt, atan2, radians
import folium
from folium.features import DivIcon
from folium.plugins import MousePosition

def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0
    lat1_r = radians(lat1)
    lon1_r = radians(lon1)
    lat2_r = radians(lat2)
    lon2_r = radians(lon2)
    dlon = lon2_r - lon1_r
    dlat = lat2_r - lat1_r
    a = sin(dlat/2)**2 + cos(lat1_r) * cos(lat2_r) * sin(dlon/2)**2
    c = 2 * atan2(sqrt(a), sqrt(1-a))
    return R * c

# Launch site
launch_site_lat = 28.56230
launch_site_lon = -80.57736

# Closest coastline (adjust using mouse position on map)
coastline_lat = 28.56230
coastline_lon = -80.56900  # ← Get this from the map!

# Calculate distance
distance = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

print(f"Distance to coastline: {distance:.2f} km")

# Create map
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=15)

# Add markers
folium.Marker([launch_site_lat, launch_site_lon], popup="Launch Site", icon=folium.Icon(color='red')).add_to(site_map)

folium.Marker([coastline_lat, coastline_lon], icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0), html=f'<div style="font-size:12px;color:#d35400;"><b>{distance:.2f} KM</b></div>')).add_to(site_map)

# Add Polyline
folium.PolyLine([[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]], color='blue', weight=3).add_to(site_map)

# Mouse position
mouse_position = MousePosition(position='topright', prefix='Lat:', lat_formatter="function(num) {return L.Util.formatNum(num, 5);}", lng_formatter="function(num) {return L.Util.formatNum(num, 5);}")
site_map.add_child(mouse_position)

site_map

Distance to coastline: 0.82 km

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [22]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site

import folium
from folium.features import DivIcon
from folium.plugins import MousePosition
from math import sin, cos, sqrt, atan2, radians

# Function to calculate distance
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0
    lat1_r = radians(lat1)
    lon1_r = radians(lon1)
    lat2_r = radians(lat2)
    lon2_r = radians(lon2)
    dlon = lon2_r - lon1_r
    dlat = lat2_r - lat1_r
    a = sin(dlat / 2)**2 + cos(lat1_r) * cos(lat2_r) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    return R * c

# Launch site coordinates (CCAFS LC-40)
launch_site_lat = 28.56230
launch_site_lon = -80.57736

# Points of interest (update with actual coordinates from your map)
points_of_interest = {
    "Coastline": [28.56230, -80.56900],
    "Highway (SR-401)": [28.56500, -80.58000],
    "Railway": [28.57000, -80.58500],
    "City (Cape Canaveral)": [28.38800, -80.60300],
    "Airport": [28.46500, -80.56700]
}

# Create map
site_map = folium.Map(location=[launch_site_lat, launch_site_lon], zoom_start=12)

# Add launch site marker
folium.Marker(
    [launch_site_lat, launch_site_lon],
    popup="LAUNCH SITE: CCAFS LC-40",
    icon=folium.Icon(color='red', icon='rocket', prefix='fa')
).add_to(site_map)

# Add markers for each point of interest with distance line
for name, coord in points_of_interest.items():
    # Calculate distance
    distance = calculate_distance(launch_site_lat, launch_site_lon, coord[0], coord[1])
    
    # Add marker with distance label
    folium.Marker(
        coord,
        popup=f"{name}<br>Distance: {distance:.2f} km",
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, -15),
            html=f'<div style="font-size: 11px; color:blue; background:white; padding:2px; border-radius:5px;"><b>{name}<br>{distance:.2f} km</b></div>'
        )
    ).add_to(site_map)
    
    # Draw line between launch site and point of interest
    folium.PolyLine(
        [[launch_site_lat, launch_site_lon], coord],
        color='purple',
        weight=2,
        opacity=0.6,
        popup=f"Distance: {distance:.2f} km"
    ).add_to(site_map)

# Add Mouse Position
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)
site_map.add_child(mouse_position)

# Display map
site_map

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
YES (0.5-2 km) – Transport rocket components
*   Are launch sites in close proximity to highways?
YES (0.5-2 km) – Transport rocket components
*   Are launch sites in close proximity to coastline?
YES (0.8-3 km) – Launch over water for safety
*   Do launch sites keep certain distance away from cities?
YES (5-15 km away) – Safety buffer zone

Also please try to explain your findings.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>